[project]
name = "pdfsummarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-agents>=0.6.1",
    "streamlit",
    "pypdf2",
    "openai"
]
